services:
  app:
    build:
      context: .
    command: bash start-dev.sh
    environment:
      DB_URL: jdbc:postgresql://db:5432/api-barber-shop
      DB_USER: api-barber-shop
      DB_PASSWORD: api-barber-shop
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/api-barber-shop:z
    depends_on:
      db:
        condition: service_healthy
    networks:
      - barber-shop-net

  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: api-barber-shop
      POSTGRES_PASSWORD: api-barber-shop
      POSTGRES_DB: api-barber-shop
    ports:
      - "5432:5432"
    networks:
      - barber-shop-net
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api-barber-shop"]
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  barber-shop-net:
    name: barber-shop-net
    external: true

volumes:
  db:
